--[[
Format: workspaces = { {"workspace1","workspace2",...}, {layoutForWorkspace1, layoutForWorkspace2} }
--]]

return
{
    {
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9"
    },
    {
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
        modules.awful.layout.suit.tile,
    },
}